services:

  db:
    image: postgres:16
    container_name: kanban_db

    environment:
      POSTGRES_USER: istore
      POSTGRES_PASSWORD: postgre
      POSTGRES_DB: ansar

    ports:
      - "5434:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .

    container_name: kanban_app

    depends_on:
      - db

    ports:
      - "8000:8000"

    volumes:
      - .:/code

volumes:
  postgres_data: